export const REASON = Object.freeze({
  // PARTIAL-capable (only when --allow-partial)
  MISSING_SEAL: 'MISSING_SEAL',
  TRUNCATED_LAST_LINE: 'TRUNCATED_LAST_LINE',

  // FAIL: Parse/structure
  BAD_JSON: 'BAD_JSON',
  EMPTY_FILE: 'EMPTY_FILE',
  MISSING_RUN: 'MISSING_RUN',
  MISSING_FIELD: 'MISSING_FIELD',
  BAD_RECORD_TYPE: 'BAD_RECORD_TYPE',
  UNSUPPORTED_VERSION: 'UNSUPPORTED_VERSION',

  // FAIL: Ordering
  SEGMENT_AFTER_TRACE: 'SEGMENT_AFTER_TRACE',

  // FAIL: Integrity/chain
  SEGMENT_HASH_MISMATCH: 'SEGMENT_HASH_MISMATCH',
  GAP_HASH_MISMATCH: 'GAP_HASH_MISMATCH',
  CHAIN_MISMATCH: 'CHAIN_MISMATCH',
  UNSUPPORTED_ALGO: 'UNSUPPORTED_ALGO',
  ROOT_MISMATCH: 'ROOT_MISMATCH',
  TERMINAL_MISMATCH: 'TERMINAL_MISMATCH'
});

export function isPartialCapable(reason) {
  return reason === REASON.MISSING_SEAL || reason === REASON.TRUNCATED_LAST_LINE;
}
